#!/usr/bin/python3
#import oct2py
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import json
import re
#import datetime
from datetime import timedelta
import requests
import pandas as pd
from datetime import datetime
from datetime import timedelta
import time
now = datetime.now()
twodago = datetime.now() - timedelta(days=2)
twodtimestr = datetime.isoformat(twodago).split('.')[0]
twodtimestr = twodtimestr + 'Z'
print(twodtimestr)

timestr = datetime.isoformat(now).split('.')[0]
timestr = timestr + 'Z'
url = "https://geomag.usgs.gov/ws/data/?id=BOU&elements=H&format=json&starttime=" + twodtimestr + "&endtime=" + timestr
data = requests.get(url).text
data = data.replace(",null","")
jsondata = json.loads(data)
fildat = jsondata["values"][0]["values"]
fildattime = jsondata["times"]
fildattime = fildattime[:len(fildat)];
fildattime = pd.to_datetime(fildattime)
plt.plot(fildattime, fildat, color='blue', linewidth=0.75);
plt.title('Boulder Magnetometer - 48 Hours')
plt.xlabel('Time')
plt.ylabel('nT')
plt.show()
	
